//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileCenterApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MobileCenterApiEntities : DbContext
    {
        public MobileCenterApiEntities()
            : base("name=MobileCenterApiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TableComplaint> TableComplaints { get; set; }
        public virtual DbSet<TableContact> TableContacts { get; set; }
        public virtual DbSet<TableEmployee> TableEmployees { get; set; }
        public virtual DbSet<TableMobile> TableMobiles { get; set; }
    }
}
