//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileCenterApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableMobile
    {
        public int id { get; set; }
        public string CompanyName { get; set; }
        public string ProductModel { get; set; }
        public string Features { get; set; }
        public string Price { get; set; }
        public string Qty { get; set; }
    }
}
